spring:
  application:
    name: discodeit

discodeit:
  repository:
    type: file  # jcf | file
    file-directory: .discodeit
    binaryContent-json-path: "binaryContents.json"
    channel-json-path: "channels.json"
    message-json-path: "messages.json"
    readStatus-json-path: "readStatuses.json"
    user-json-path: "users.json"
    userStatus-json-path: "userStatuses.json"

